# Generated by Django 4.0.4 on 2022-04-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTOPILOT_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultants',
            name='name',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='consultants',
            name='prenom',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
