# Generated by Django 4.0.4 on 2022-04-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AUTOPILOT_APP', '0002_consultants_name_alter_consultants_prenom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultants',
            old_name='name',
            new_name='nom',
        ),
    ]
