# Generated by Django 4.0.4 on 2022-04-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AUTOPILOT_APP', '0003_rename_name_consultants_nom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consultants',
        ),
    ]
