# Generated by Django 4.0.4 on 2022-04-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AUTOPILOT_APP', '0004_delete_consultants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultants',
            fields=[
                ('idConsultant', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(default='NULL', max_length=100)),
                ('prenom', models.CharField(default='NULL', max_length=100)),
            ],
        ),
    ]
