# Generated by Django 4.0.4 on 2022-04-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AUTOPILOT_APP', '0005_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consultants',
            new_name='Consultant',
        ),
    ]
