# Generated by Django 4.0.4 on 2022-04-19 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AUTOPILOT_APP', '0006_rename_consultants_consultant'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('idTimeSheet', models.BigAutoField(primary_key=True, serialize=False)),
                ('annee', models.IntegerField(max_length=4)),
                ('semaine', models.IntegerField(max_length=2)),
                ('idConsultant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AUTOPILOT_APP.consultant')),
            ],
        ),
    ]
