# Generated by Django 4.0.4 on 2022-04-19 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AUTOPILOT_APP', '0007_timesheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('idMission', models.BigAutoField(primary_key=True, serialize=False)),
                ('startDate', models.TimeField()),
                ('endDate', models.TimeField()),
                ('nomMission', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='annee',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='semaine',
            field=models.SmallIntegerField(),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='idMission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AUTOPILOT_APP.mission'),
        ),
    ]
