# Generated by Django 4.0.4 on 2022-04-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTOPILOT_APP', '0008_mission_alter_timesheet_annee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='startDate',
            field=models.DateField(),
        ),
    ]
