# Generated by Django 4.0.4 on 2022-05-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AUTOPILOT_APP', '0014_consultant_email_consultant_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultant',
            options={'managed': False},
        ),
    ]
