# Generated by Django 4.0.4 on 2022-05-27 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AUTOPILOT_APP', '0015_alter_consultant_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consultant',
            table='consultant',
        ),
    ]
