# Generated by Django 4.0.4 on 2022-05-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AUTOPILOT_APP', '0016_alter_consultant_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'managed': False},
        ),
    ]
