# Generated by Django 4.0.4 on 2022-05-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AUTOPILOT_APP', '0018_missionstype_alter_mission_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheet',
            options={'managed': False},
        ),
    ]
