# Generated by Django 4.0.4 on 2022-05-27 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AUTOPILOT_APP', '0019_alter_timesheet_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='timesheet',
            table='timeSheet',
        ),
    ]
