# Generated by Django 4.0.4 on 2022-06-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTOPILOT_APP', '0020_alter_timesheet_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitesMissions',
            fields=[
                ('idActivitesMissions', models.AutoField(db_column='idActivitesMissions', primary_key=True, serialize=False)),
                ('tjm', models.FloatField(blank=True, null=True)),
                ('estimationCharge', models.FloatField(blank=True, db_column='estimationCharge', null=True)),
            ],
            options={
                'db_table': 'activitesMissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActivitesType',
            fields=[
                ('idActivitesType', models.AutoField(db_column='idActivitesType', primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activitesType',
                'managed': False,
            },
        ),
    ]
