# Generated by Django 4.0.4 on 2022-06-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTOPILOT_APP', '0021_activitesmissions_activitestype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competences',
            fields=[
                ('idCompetence', models.AutoField(db_column='idCompetence', primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'competences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultantsCompetences',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'consultantsCompetences',
                'managed': False,
            },
        ),
    ]
